version: '3.8'

services:
  luizalabs_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  luizalabs_app:
    image: luizalabs_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - luizalabs_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@luizalabs_database:5432/app_db

volumes:
  pgdata: