"""deletar em forma de cascata

Revision ID: 0029aba62aea
Revises: 1fd6e3d5ed2c
Create Date: 2024-09-22 19:46:26.294799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0029aba62aea'
down_revision: Union[str, None] = '1fd6e3d5ed2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_product_favorites_user_id_fkey', 'user_product_favorites', type_='foreignkey')
    op.create_foreign_key(None, 'user_product_favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_product_favorites', type_='foreignkey')
    op.create_foreign_key('user_product_favorites_user_id_fkey', 'user_product_favorites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
